=== MarcalHerraiz/M04Ejercicios/HerraizMarcal_recetas.dtd
<!ELEMENT recetas (receta+)>
<!ELEMENT receta ((nombre | categoria), infogeneral?, ingredientes, preparacion)>
<!ATTLIST recetas autor CDATA #FIXED "MarÃ§al Herraiz">
<!ATTLIST receta idReceta ID #REQUIRED fechaAlta CDATA #IMPLIED)>
<!ELEMENT nombre (#PCDATA)>
<! ELEMENT categoria (#PCDATA | subcategoria)*> 
<!-- <! ELEMENT categoria (#PCDATA, subcategoria)?> -->
<!ELEMENT subcategoria (#PCDATA)>
<!ELEMENT infogeneral (#PCDATA)>
<!ELEMENT infogeneral (foto*, enlace, comensales, tiempo, dificultad, descripcion?)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT enlace (#PCDATA)>
<!ELEMENT comensales (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ATTLIST tiempo unidadTiempo (minutos | horas) "minutos">
<!ELEMENT dificultad (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT ingredientes (#PCDATA)>
<!ELEMENT ingredientes (ingrediente)>
<!ATTLIST ingrediente cantidad CDATA #REQUIRED unidadDeMedida (gramo | taza | cucharada | cuchara | mililitro) "gramo">
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT preparacion (#PCDATA)>
<!ELEMENT preparacion (paso)>
<!ELEMENT paso (#PCDATA)>
<!ATTLIST paso orden IDREF #REQUIRED)>

=== MarcalHerraiz/M04Ejercicios/HerraizMarcal_recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM "HerraizMarcal_recetas.dtd">
<recetas autor="Marçal Herraiz">
  <receta idReceta="987654" fechaAlta="10/12/2015">
    <nombre>Crema de calabacín</nombre>
    <categoria>
    cena
      <subcategoria/>
    </categoria>
    <infogeneral>
      <foto>https://www.recetasderechupete.com/wp-content/uploads/2015/01/crema_calabacin.jpg</foto>
      <enlace>https://www.recetasderechupete.com/crema-de-calabacin/12152/</enlace>
      <comensales>4</comensales>
      <tiempo unidadTiempo="minutos">40</tiempo>
      <dificultat>Fácil</dificultat>
      <descripcion>Receta perfecta para una cena saludable</descripcion>
    </infogeneral>
    <ingredientes>
      <ingrediente cantidad="600" unidadDeMedida="gramo">calabacín</ingrediente>
            <ingrediente cantidad="100" unidadDeMedida="gramo">cebolla</ingrediente>
            <ingrediente cantidad="100" unidadDeMedida="gramo">patata </ingrediente>
            <ingrediente cantidad="100" unidadDeMedida="mililitro">nata</ingrediente>
            <ingrediente cantidad="250" unidadDeMedida="mililitro">caldo de verduras </ingrediente>
            <ingrediente cantidad="2" unidadDeMedida="cucharada">Aceite de oliva</ingrediente>
    </ingredientes>
    <preparacion>
      <paso orden="1">Comenzamos por pelar la cebolla y picarla en juliana. Lavamos la patata, la pelamos y la cortamos en dados. En una cazuela con una lámina de aceite de oliva virgen extra. Las sofreímos durante 5 minutos a fuego medio. Salamos al gusto. 
            Para facilitar su manejo, cortamos los calabacines en varios trozos. Con un cuchillo bien afilado vamos quitando la piel, y luego los picamos en dados pequeños.</paso>
      <paso orden="2">Los añadimos a la cazuela. Con la piel restante, vamos a picar un poco de ella bien fina y también la echamos junto al resto de ingredientes. De esta manera le daremos un toque de color al resultado final. 
            Mezclamos y seguimos cocinando unos 5 minutos a fuego medio, así irán ablandando las hortalizas. Salamos ligeramente de nuevo. Vertemos ahora el caldo de verduras o en su defecto, si no tenéis caldo, agua caliente, de modo que cubra todas las verduras.</paso>
      <paso orden="3">Cocemos 20 minutos a fuego medio, tapando la cazuela, de manera que esté siempre hirviendo suavemente, con pequeños borbotones. Pasado el tiempo, vamos a darle el toque de gracia al plato. Retiramos del fuego,  añadimos la nata 
            (si la queréis más liviana emplead leche entera, y si hay intolerantes a la lactosa en casa, son leche de soja) y mezclamos bien.
             Con el calor que tiene la olla llegará para que se cocine suavemente. </paso>
       <paso orden="4">Trituramos con la batidora y vamos comprobando el punto de la crema. Queremos que quede ligera, no como un puré. Si nos ha quedado espesa, podemos añadir un poco más de caldo hasta conseguir la textura deseada.
             Y con estos sencillos pasos ya estaría lista la crema de calabacín.</paso>
    </preparacion>
  </receta>
  <receta idReceta="987784" fechaAlta="10/07/2017">
    <nombre>Frixuelos asturianos</nombre>
    <categoria>
    postres
      <subcategoria>dulce</subcategoria>
    </categoria>
    <infogeneral>
      <foto>https://www.recetasderechupete.com/wp-content/uploads/2021/02/crepes-carnaval-768x530.jpg</foto>
      <enlace>https://www.recetasderechupete.com/frixuelos-asturianos/16291/</enlace>
      <comensales>8</comensales>
      <tiempo unidadTiempo="minutos">40</tiempo>
      <dificultat>Fácil</dificultat>
      <descripcion>Los frixuelos son primos hermanos de las filloas gallegas y de los crepes franceses, unas tortitas elaboradas con leche, huevos y harina que se cocinan en una sartén engrasada y que son de presencia obligada en las mesas asturianas en su Antroxu o Carnaval así como en la fiesta de Comadres.</descripcion>
    </infogeneral>
    <ingredientes>
      <ingrediente cantidad="200" unidadDeMedida="gramo">harina</ingrediente>
            <ingrediente cantidad="4" unidadDeMedida="taza">huevos</ingrediente>
            <ingrediente cantidad="500" unidadDeMedida="mililitro">leche </ingrediente>
            <ingrediente cantidad="1" unidadDeMedida="cucharada">coñac</ingrediente>
            <ingrediente cantidad="2" unidadDeMedida="cucharada">azúcar </ingrediente>            
    </ingredientes>
    <preparacion>
      <paso orden="1">En un bol batimos los huevos y añadimos las dos cucharadas de azúcar. 
      Continuamos batiendo hasta que este se haya integrado. Incorporamos la cucharada de coñac, la leche, una pizca de sal y la ralladura de limón. 
      Volvemos a batir para mezclar bien los ingredientes.</paso>
      <paso orden="2">Añadimos la harina, poco a poco, al tiempo que seguimos vamos incorporándola con la ayuda de unas varillas. Dejamos la masa en reposo durante unos 30 minutos. 
      Así conseguimos que la harina abra, y nos quede una textura como de crema ligera</paso>
      <paso orden="3">La cantidad de frixuelos resultante dependerá del tamaño de la sartén que vayamos a utilizar. Yo he usado una sartén pequeña, de unos 20 cm. de diámetro. 
      Añadimos una gota de aceite a la sartén y, con un papel de cocina, lo extendemos por toda la superficie de la base.</paso>
       <paso orden="4">Cuando la sartén esté caliente añadimos una porción de la mezcla e, inclinando la sartén hacemos que cubra toda la superficie de la base de la sartén. La cantidad para una sartén pequeña es, más o menos, un poco más de la mitad del volumen de un cucharón de cocina.
       Dejamos, a temperatura medio alta, que se vaya haciendo el frixuelo. Cuando vemos que los bordes empiezan a despegarse o tostarse, le daremos la vuelta y dejamos que se cocine 30 o 40 segundos más. 
       A medida que los vayáis preparando veréis el punto en el que está listo de forma muy fácil, no os preocupéis.</paso>
       <paso orden="5">Vamos colocando los frixuelos en un plato y espolvoreándolo con azúcar a medida que los vamos haciendo. Colocando unos sobre otros. 
       Repetimos la operación, mojando la sartén con una nueva gota de aceite cada vez que os pongamos con un nuevo frixuelo.</paso>
    </preparacion>
  </receta>
  <receta idReceta="982731" fechaAlta="25/03/2020">
    <nombre>Flor de hojaldre con chocolate</nombre>
    <categoria>
    postres
      <subcategoria>dulce</subcategoria>
    </categoria>
    <infogeneral>
      <foto>https://www.recetasderechupete.com/wp-content/uploads/2021/02/crepes-carnaval-768x530.jpg</foto>
      <enlace>https://www.recetasderechupete.com/frixuelos-asturianos/16291/</enlace>
      <comensales>8</comensales>
      <tiempo unidadTiempo="minutos">30</tiempo>
      <dificultat>Fácil</dificultat>
      <descripcion>Los frixuelos son primos hermanos de las filloas gallegas y de los crepes franceses, unas tortitas elaboradas con leche, huevos y harina que se cocinan en una sartén engrasada y que son de presencia obligada en las mesas asturianas en su Antroxu o Carnaval así como en la fiesta de Comadres.</descripcion>
    </infogeneral>
    <ingredientes>
      <ingrediente cantidad="500" unidadDeMedida="gramo">hojaldre</ingrediente>
            <ingrediente cantidad="250" unidadDeMedida="gramo">crema de cacao</ingrediente>
            <ingrediente cantidad="1" unidadDeMedida="taza">huevo </ingrediente>
            <ingrediente cantidad="100" unidadDeMedida="gramo">azúcar</ingrediente>
    </ingredientes>
    <preparacion>
      <paso orden="1">Sobre un papel vegetal ponemos una de las planchas de hojaldre. Con la ayuda de un rodillo extendemos ligeramente la plancha.
      Untamos la crema de cacao por la superficie de la plancha. Debemos dejar un perímetro de 2 cm. sin relleno. Es recomendable calentar previamente la crema de cacao, así será mucho más fácil de extender sobre el hojaldre.
      Cubrimos con la segunda plancha de hojaldre que previamente habremos estirado sobre un papel vegetal.</paso>
      <paso orden="2">En el centro de las planchas ponemos un vaso. Este vaso nos servirá de límite en el momento de realizar los cortes de las porciones. Así, con la punta de un cuchillo cortamos las panchas en 16 partes, desde la base del vaso hasta el final de la masa.
      Giramos cada uno de los &quot;pétalos&quot; sobre sí mismos y en la misma dirección.</paso>
      <paso orden="3">Pintamos la superficie de la flor con huevo batido. Precalentamos el horno a 200º C</paso>
       <paso orden="4">Colocamos las masas con la base de papel vegetal sobre la rejilla del horno. Horneamos a 200º C con calor arriba-abajo y aire durante 25 minutos.</paso>       
    </preparacion>
  </receta>
</recetas>
